"""
Integration tests for AI summary update workflow.

Tests the end-to-end process of updating book summaries
using AI generation, including database updates and error handling.
"""

from unittest.mock import Mock, patch

import pytest
from sqlalchemy import select

from app.models.book import Book
from app.models.enums import BookStatus


@pytest.mark.asyncio
async def test_update_summaries_for_books_with_poor_summaries(async_session):
    """Test that books with poor summaries are updated correctly."""
    book1 = Book(
        title="Clean Code",
        author="Robert C. Martin",
        isbn="9780132350884",
        summary="Published by Prentice Hall",
        status=BookStatus.AVAILABLE,
    )
    book2 = Book(
        title="The Pragmatic Programmer",
        author="Andy Hunt",
        isbn="9780201616224",
        summary=None,
        status=BookStatus.AVAILABLE,
    )
    book3 = Book(
        title="Existing Good Summary",
        author="Test Author",
        isbn="1234567890",
        summary="This book provides valuable insights into modern software development practices and methodologies.",
        status=BookStatus.AVAILABLE,
    )

    async_session.add_all([book1, book2, book3])
    await async_session.commit()

    mock_response = Mock()
    mock_response.choices = [Mock(message=Mock(content="A comprehensive guide to writing maintainable code."))]

    mock_client = Mock()
    mock_client.chat.send.return_value = mock_response
    mock_client.__enter__ = Mock(return_value=mock_client)
    mock_client.__exit__ = Mock(return_value=False)

    with patch("app.services.ai_service.OpenRouter", return_value=mock_client):
        from scripts.update_book_summaries import update_book_summaries

        await update_book_summaries(db=async_session)

    await async_session.commit()
    result = await async_session.execute(select(Book))
    updated_books = list(result.scalars().all())

    book1_updated = next(b for b in updated_books if b.title == "Clean Code")
    book2_updated = next(b for b in updated_books if b.title == "The Pragmatic Programmer")
    book3_updated = next(b for b in updated_books if b.title == "Existing Good Summary")

    expected_summary = (
        "A comprehensive guide to writing maintainable code.\n\n*Note: This summary was generated by AI.*"
    )
    assert book1_updated.summary == expected_summary
    assert book2_updated.summary == expected_summary
    expected_summary = (
        "This book provides valuable insights into modern software development practices and methodologies."
    )
    assert book3_updated.summary == expected_summary


@pytest.mark.asyncio
async def test_update_summaries_handles_api_failures_gracefully(async_session):
    """Test that API failures don't stop the entire update process."""
    book1 = Book(title="Book One", author="Author One", isbn="1111111111", summary=None, status=BookStatus.AVAILABLE)
    book2 = Book(title="Book Two", author="Author Two", isbn="2222222222", summary=None, status=BookStatus.AVAILABLE)

    async_session.add_all([book1, book2])
    await async_session.commit()

    call_count = 0

    def mock_send(*args, **kwargs):
        nonlocal call_count
        call_count += 1
        if call_count == 1:
            raise Exception("API error")
        mock_response = Mock()
        mock_response.choices = [Mock(message=Mock(content="Good summary for book two"))]
        return mock_response

    mock_client = Mock()
    mock_client.chat.send.side_effect = mock_send
    mock_client.__enter__ = Mock(return_value=mock_client)
    mock_client.__exit__ = Mock(return_value=False)

    with patch("app.services.ai_service.OpenRouter", return_value=mock_client):
        from scripts.update_book_summaries import update_book_summaries

        await update_book_summaries(db=async_session)

    await async_session.commit()
    result = await async_session.execute(select(Book))
    updated_books = list(result.scalars().all())

    book1_updated = next(b for b in updated_books if b.title == "Book One")
    book2_updated = next(b for b in updated_books if b.title == "Book Two")

    assert book1_updated.summary is None
    expected_summary = "Good summary for book two\n\n*Note: This summary was generated by AI.*"
    assert book2_updated.summary == expected_summary


@pytest.mark.asyncio
async def test_update_summaries_is_idempotent(async_session):
    """Test that running the update twice doesn't cause issues."""
    book = Book(title="Test Book", author="Test Author", isbn="9999999999", summary=None, status=BookStatus.AVAILABLE)

    async_session.add(book)
    await async_session.commit()

    mock_response = Mock()
    mock_response.choices = [
        Mock(message=Mock(content="First AI generated summary that is long enough to be considered good quality"))
    ]

    mock_client = Mock()
    mock_client.chat.send.return_value = mock_response
    mock_client.__enter__ = Mock(return_value=mock_client)
    mock_client.__exit__ = Mock(return_value=False)

    with patch("app.services.ai_service.OpenRouter", return_value=mock_client):
        from scripts.update_book_summaries import update_book_summaries

        await update_book_summaries(db=async_session)

    await async_session.commit()
    result = await async_session.execute(select(Book).where(Book.title == "Test Book"))
    book_after_first_run = result.scalar_one()
    first_summary = book_after_first_run.summary

    expected_summary = (
        "First AI generated summary that is long enough to be considered good quality"
        "\n\n*Note: This summary was generated by AI.*"
    )
    assert first_summary == expected_summary

    mock_response.choices = [Mock(message=Mock(content="Second AI generated summary that is also long enough"))]

    mock_client = Mock()
    mock_client.chat.send.return_value = mock_response
    mock_client.__enter__ = Mock(return_value=mock_client)
    mock_client.__exit__ = Mock(return_value=False)

    with patch("app.services.ai_service.OpenRouter", return_value=mock_client):
        await update_book_summaries(db=async_session)

    await async_session.commit()
    result = await async_session.execute(select(Book).where(Book.title == "Test Book"))
    book_after_second_run = result.scalar_one()
    second_summary = book_after_second_run.summary

    assert second_summary == first_summary
    assert "*Note: This summary was generated by AI.*" in second_summary
    mock_client.chat.send.assert_not_called()


@pytest.mark.asyncio
async def test_update_summaries_with_no_books(async_session):
    """Test that the script handles an empty database gracefully."""
    mock_response = Mock()
    mock_response.choices = [Mock(message=Mock(content="Test summary"))]

    mock_client = Mock()
    mock_client.chat.send.return_value = mock_response
    mock_client.__enter__ = Mock(return_value=mock_client)
    mock_client.__exit__ = Mock(return_value=False)

    with patch("app.services.ai_service.OpenRouter", return_value=mock_client):
        from scripts.update_book_summaries import update_book_summaries

        await update_book_summaries(db=async_session)

    await async_session.commit()
    result = await async_session.execute(select(Book))
    books = list(result.scalars().all())

    assert len(books) == 0
    mock_client.chat.send.assert_not_called()
