"""add cover_image and summary to books

Revision ID: b32298f31227
Revises: 423444c5292d
Create Date: 2026-01-22 14:20:35.751823

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b32298f31227"
down_revision: Union[str, Sequence[str], None] = "423444c5292d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("books", sa.Column("cover_image", sa.String(length=500), nullable=True))
    op.add_column("books", sa.Column("summary", sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("books", "summary")
    op.drop_column("books", "cover_image")
    # ### end Alembic commands ###
